name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build Vite React App
      - name: Build React App
        run: npm run build

      # Remove old deployed files
      - name: Clean public_html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/${{ secrets.USERNAME }}/public_html/*

      # Upload latest build files
      - name: Deploy to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/home/${{ secrets.USERNAME }}/public_html"
          strip_components: 1

      # Deployment complete
      - name: Deployment Success
        run: echo "Deployment completed successfully"